#!/bin/sh
set -eu

APP_DIR="/opt/antivirus-project"
DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/antivirus-project"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/antivirus-project"

umask 077
mkdir -p "$DATA_DIR" "$STATE_DIR"
cd "$DATA_DIR"

exec "$APP_DIR/antivirus-project" "$@" >>"$STATE_DIR/antivirus-project.log" 2>&1
